export const APP_LAYOUT_PARAMS = {
  navHeight: 50,
  tabHeight: 40,
  sideWidth: 240,
  sideCollapsedWidth: 64,
  sideMenuCollapsedWidth: 48,
  contentPadding: 20,
  footHeight: 50,
  backTopRight: 20,
  backTopBottom: 75,
  backTopvisibilityHeight: 250,
  settingsDrawerRight: 20,
  settingsDrawerBottom: 350,
  settingsDrawerWidth: 330,
}
