// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AvatarUpload: typeof import('./components/AvatarUpload.vue')['default']
    DarkToggle: typeof import('./components/DarkToggle.vue')['default']
    Plum: typeof import('./components/Plum.vue')['default']
    PreLoaded: typeof import('./components/PreLoaded.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollWrapper: typeof import('./components/ScrollWrapper.vue')['default']
  }
}
